title: Aurelianix
email: hi@aurealianix.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Leo. I like tech, music machines. Reach out to me at hi at aurealianix dot com
  if you would like to connect.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.aurelianix.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  leononame

# Build settings
theme: jekyll-whiteglass
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
